### ISSUE TITLE
Write support

### ISSUE THREAD

**Issue by NorthWindH** [evilncrazy/ctoml#1]
Any plans for supporting writing out to a stream/file/etc...?

**Comment by evilncrazy** [comment]
Yes, I'm planning to be able to write TOML files using ctoml, most likely using C++ streams.

**Comment by nbigaouette** [comment]
Any news on this?
Also, you don't have any license file. What license is this work?

**Comment by evilncrazy** [comment]
Thanks for spotting that! Added licence. As for the the write support, I wanted to wait until I've managed to rewrite the code in a more idiomatic C++ way (e.g. inheritance, smart pointers, iterators, streams). I've updated the repo with the rewritten code (API's changed a bit), but now has basic support for writing to a stream.
