### ISSUE TITLE
Collision between time_t and int64_t class member redeclaration

### ISSUE THREAD

**Issue by toroidal-code** [evilncrazy/ctoml#2]
Compilation fails with:
clang++ -Wall -Wextra -pedantic -std=c++0x -g -c ../src/main.cc
In file included from ../src/main.cc:1:
In file included from ../src/include/toml.h:4:
../src/include/tomlvalue.h:57:9: error: class member cannot be redeclared
   bool operator == (const time_t val);  
        ^
../src/include/tomlvalue.h:54:9: note: previous declaration is here
   bool operator == (const int64_t val);
        ^
2 warnings and 1 error generated.
make: **\* [main.o] Error 1

On my system int64_t and time_t are the same, thus preventing redefinition.

**Comment by evilncrazy** [comment]
Thanks for that! I've now changed it so that comparison with dates is done using the tm struct, rather than time_t which gets confusing with int types.

**Comment by toroidal-code** [comment]
Thanks, that seems to have fixed it.
