### ISSUE TITLE
Parsing examples fails

### ISSUE THREAD

**Issue by nbigaouette** [evilncrazy/ctoml#6]
Not sure if I'm doing something wrong here, but I get errors parsing the examples:

```
$ cd build
$ make
$ ./ctoml ../test/tests.toml 
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_S_construct null not valid
Abandon (core dumped)
```

The issue is caused by using "argv[2]" which is non-existent. "argv[1]" points to the first command line argument.

Additionally, the example from the readme fails too. I get a seg fault. The error is simply that there is no toml file corresponding. It might be better to fail more gracefully in these case.

**Comment by evilncrazy** [comment]
_facepalm_ yeah should be "argv[1]". Also made it so that if parser.good() is false, then parser.parse() will return an empty document.
