### ISSUE TITLE
Writting title to stream fails on Windows

### ISSUE THREAD

**Issue by nbigaouette** [evilncrazy/ctoml#7]
When the toml data contains a title, writing the data to a stream will fail with a "Debug assertion failed". The exact popup can be seen here: http://imgur.com/HRJGQpe

The issue is triggered when inserting a pair in the map in n toml.cc at line 51:

```
map.insert(std::make_pair(it->first, it->second));
```

I think it's the insert() that is causing problem, not the make_pair(). I found the toml's title to be problematic by printing it->first and it->second; the assertion fails when the title is being inserted.

By removing the title from the toml file, it does work.

**Comment by evilncrazy** [comment]
Yeah it was a weird logic bug. The comparator for the std::map has to be transitive, but it wasn't. Fixed it now.
